# personal SSH shortcuts
alias alcyone='ssh brianvh@alcyone.dartmouth.edu'
alias area51='ssh brianvh@area51.dartmouth.edu'
alias badlands='ssh brianvh@badlands.dartmouth.edu'
alias bayou='ssh brianvh@bayou.dartmouth.edu'
alias cobweb='ssh brianvh@cobweb.dartmouth.edu'
alias dbs='ssh dbsadmin@merrimack.dartmouth.edu'
alias dev='ssh brianvh@dev.dartmouth.edu'
alias devw='ssh webops@dev.dartmouth.edu'
alias electra='ssh brianvh@electra.dartmouth.edu'
alias evg='ssh brianvh@everglades.dartmouth.edu'
alias grass='ssh brianvh@grassland.dartmouth.edu'
alias klatch='ssh brianvh@klatch.dartmouth.edu'
alias maia='ssh brianvh@maia.dartmouth.edu'
alias media='ssh brianvh@media.dartmouth.edu'
alias news='ssh brianvh@merrimack.dartmouth.edu'
alias plateau='ssh brianvh@plateau.dartmouth.edu'
alias search='ssh brianvh@search.dartmouth.edu'
alias scrubland='ssh brianvh@scrubland.dartmouth.edu'
alias taygete='ssh brianvh@taygete.dartmouth.edu'
alias torridon='ssh brianvh@torridon.dartmouth.edu'
alias tundra='ssh brianvh@tundra.dartmouth.edu'
alias veldt='ssh brianvh@veldt.dartmouth.edu'
alias webapp='ssh brianvh@webapp.dartmouth.edu'
alias www='ssh brianvh@www.dartmouth.edu'

# Rails app SSH shortcuts
alias b_dfd='ssh dfd@badlands.dartmouth.edu'
alias b_dofcomm='ssh dofcomm@badlands.dartmouth.edu'
alias b_dtaward='ssh dtaward@badlands.dartmouth.edu'
alias b_facballots='ssh facballots@badlands.dartmouth.edu'
alias b_hosting='ssh hosting@badlands.dartmouth.edu'
alias b_inyourcity='ssh inyourcity@badlands.dartmouth.edu'
alias b_itrack='ssh itrack@badlands.dartmouth.edu'
alias b_scholars='ssh scholars@badlands.dartmouth.edu'
alias b_studygroups='ssh studygroups@badlands.dartmouth.edu'
alias b_ugresearch='ssh ugresearch@badlands.dartmouth.edu'
alias b_wisp='ssh wisp@badlands.dartmouth.edu'
alias b_writing='ssh writing@badlands.dartmouth.edu'
alias t_frontier='ssh frontier@tundra.dartmouth.edu'
alias t_ists='ssh ists@tundra.dartmouth.edu'
alias t_ugr='ssh ugresearch@tundra.dartmouth.edu'
alias t_urchin='ssh urchin@tundra.dartmouth.edu'

# push_key
push_key() {
  ssh $1 'cat id_rsa.pub >> .ssh/authorized_keys ; rm id_rsa.pub'
}
